@extends('layouts.app')
@section('content')
<section class="card">
    <div style="display:flex;justify-content:space-between;gap:16px;align-items:center"><div><h1>{{ $project->title }}</h1><p>{{ $project->code }} · {{ $project->customer?->full_name ?? 'بدون مشتری' }} · {{ $project->status }}</p></div>@can('update',$project)<a class="button" href="{{ route('management.edit',['projects',$project->id]) }}">ویرایش پروژه</a>@endcan</div>
    <div class="stat-grid"><div class="stat"><strong>{{ $progress }}٪</strong><span>پیشرفت تسک‌ها</span></div><div class="stat"><strong>{{ $tasks->count() }}</strong><span>کل تسک‌ها</span></div><div class="stat"><strong>{{ $tasks->where('status','completed')->count() }}</strong><span>تکمیل‌شده</span></div><div class="stat"><strong>{{ $overdueCount }}</strong><span>عقب‌افتاده</span></div></div>
    <p>شروع: <span data-jalali-value="{{ $project->planned_start_date?->format('Y-m-d') }}">—</span> · پایان: <span data-jalali-value="{{ $project->planned_end_date?->format('Y-m-d') }}">—</span></p>
    <p>مدیران: {{ $project->managers->pluck('full_name')->join('، ') ?: '—' }} | دپارتمان‌ها: {{ $project->departments->pluck('name')->join('، ') ?: '—' }}</p>
</section>
<section class="card" style="margin-top:20px"><h2>خلاصه مالی</h2><div class="stat-grid"><div class="stat"><strong>{{ number_format($financial->get('income',0)+$financial->get('receivable',0)) }}</strong><span>درآمد/مطالبات</span></div><div class="stat"><strong>{{ number_format($financial->get('expense',0)+$financial->get('payable',0)+$financial->get('payroll_payment',0)) }}</strong><span>هزینه/بدهی/حقوق</span></div><div class="stat"><strong>{{ number_format($project->contract_total_amount) }}</strong><span>مبلغ قرارداد</span></div><div class="stat"><strong>{{ number_format($project->budget_amount) }}</strong><span>بودجه</span></div></div></section>
<section class="card" style="margin-top:20px"><h2>ساختار اجرایی پروژه</h2>@forelse($project->items as $item)<details open><summary><strong>{{ $item->title }}</strong> — {{ $item->progress_percent }}٪</summary>@foreach($item->subitems as $subitem)<div style="margin:14px 22px"><strong>{{ $subitem->title }}</strong> — {{ $subitem->progress_percent }}٪<table><thead><tr><th>تسک</th><th>مسئولان</th><th>وضعیت</th><th>پیشرفت</th><th>سررسید</th></tr></thead><tbody>@forelse($subitem->tasks as $task)<tr><td>{{ $task->title }}</td><td>{{ $task->assignees->pluck('full_name')->join('، ') ?: '—' }}</td><td>{{ $task->status }}</td><td>{{ $task->progress_percent }}٪</td><td><span data-jalali-value="{{ $task->due_date?->format('Y-m-d') }}">—</span></td></tr>@empty<tr><td colspan="5">تسکی ثبت نشده است.</td></tr>@endforelse</tbody></table></div>@endforeach</details>@empty<p>هنوز آیتمی ثبت نشده است.</p>@endforelse</section>
<section class="card" style="margin-top:20px"><h2>قراردادها</h2><table><thead><tr><th>شماره</th><th>عنوان</th><th>نوع</th><th>مبلغ</th><th>تاریخ</th></tr></thead><tbody>@forelse($project->contracts as $contract)<tr><td>{{ $contract->contract_no ?: '—' }}</td><td>{{ $contract->title }}</td><td>{{ $contract->type }}</td><td>{{ number_format($contract->amount) }}</td><td><span data-jalali-value="{{ $contract->signed_date?->format('Y-m-d') }}">—</span></td></tr>@empty<tr><td colspan="5">قراردادی ثبت نشده است.</td></tr>@endforelse</tbody></table></section>
@endsection
