@extends('layouts.app')
@section('content')
<section class="card"><h1>{{ $project->title }}</h1>@if($enabled->contains('project_status') || !auth()->user()->hasRole('customer'))<p>کد: {{ $project->code }} | وضعیت: {{ $project->status }}</p>@endif<p>{{ $project->description }}</p>@role('admin')<h3>مجوز گزارش مشتری</h3>@foreach(['progress'=>'پیشرفت','project_status'=>'وضعیت پروژه','tasks_summary'=>'خلاصه تسک‌ها','contract_summary'=>'خلاصه قرارداد','income_summary'=>'خلاصه درآمد','expense_summary'=>'خلاصه هزینه','attachments'=>'فایل‌ها'] as $key=>$label)<form method="post" action="{{ route('customer.permission',$project) }}" style="display:inline-block">@csrf @method('PATCH')<input type="hidden" name="report_key" value="{{ $key }}"><input type="hidden" name="is_enabled" value="{{ $enabled->contains($key)?0:1 }}"><button>{{ $label }}: {{ $enabled->contains($key)?'فعال':'غیرفعال' }}</button></form>@endforeach@endrole</section>
@if($enabled->contains('progress') || !auth()->user()->hasRole('customer'))<section class="card" style="margin-top:20px"><h2>پیشرفت</h2>@foreach($project->items as $item)<h3>{{ $item->title }} — {{ $item->progress_percent }}٪</h3>@foreach($item->subitems as $sub)<p>{{ $sub->title }} — {{ $sub->progress_percent }}٪ | تسک‌ها: {{ $sub->tasks->count() }}</p>@endforeach @endforeach</section>@endif
@if($enabled->contains('tasks_summary'))<section class="card" style="margin-top:20px"><h2>خلاصه تسک‌ها</h2>@php($tasks=$project->items->flatMap->subitems->flatMap->tasks)<p>کل: {{ $tasks->count() }} | تکمیل‌شده: {{ $tasks->where('status','completed')->count() }} | در جریان: {{ $tasks->where('status','in_progress')->count() }}</p></section>@endif
@if($enabled->contains('contract_summary'))<section class="card" style="margin-top:20px"><h2>خلاصه قراردادها</h2>@foreach($project->contracts as $contract)<p>{{ $contract->title }} — {{ number_format($contract->amount) }} تومان</p>@endforeach</section>@endif
@if($enabled->contains('income_summary'))<section class="card" style="margin-top:20px"><h2>خلاصه درآمد</h2><p>{{ number_format($financial->get('income',0)+$financial->get('receivable',0)) }} تومان</p></section>@endif
@if($enabled->contains('expense_summary'))<section class="card" style="margin-top:20px"><h2>خلاصه هزینه</h2><p>{{ number_format($financial->get('expense',0)+$financial->get('payable',0)+$financial->get('payroll_payment',0)) }} تومان</p></section>@endif
<section class="card" style="margin-top:20px"><h2>گفت‌وگو</h2>@foreach($project->comments->where('visibility','customer_visible') as $comment)<p><strong>{{ $comment->author?->name }}:</strong> {{ $comment->body }}</p>@endforeach<form method="post" action="{{ route('customer.comment',$project) }}">@csrf<textarea name="body" rows="3" style="width:100%" required></textarea><button>ثبت نظر</button></form></section>
@if($enabled->contains('attachments') || !auth()->user()->hasRole('customer'))<section class="card" style="margin-top:20px"><h2>فایل‌ها</h2>@foreach($project->attachments as $attachment)@if(!auth()->user()->hasRole('customer') || $attachment->visibility==='customer_visible')<p><a href="{{ route('attachments.download',$attachment) }}">{{ $attachment->original_name }}</a></p>@endif @endforeach<form method="post" enctype="multipart/form-data" action="{{ route('customer.upload',$project) }}">@csrf<input type="file" name="file" required><input name="description" placeholder="توضیح"><button>بارگذاری</button></form></section>@endif
@endsection
